### PR TITLE
Fix packge sign issue

### LINKED ISSUE #16: Signature validation failed when sign rpm with rpm-rs library
The signature validation commands(`rpm -Kv`) shows there is some issue when sign rpm with rpm-rs library:
```
❯ rpm -Kv CUnit-rust-2.1.3-21.oe1.x86_64.rpm
CUnit-rust-2.1.3-21.oe1.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID d419ba44: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA256 Signature, key ID d419ba44: BAD
    MD5 digest: OK
```
BTW, I am not sure what exactly the signature header that rpm tool is checking:
```
Header V4 RSA/SHA256 Signature, key ID d419ba44: OK  ->check the sig header of  `RPMSIGTAG_RSA` which looks good?
V4 RSA/SHA256 Signature, key ID d419ba44: BAD -> check the sig header of `RPMSIGTAG_PGP` which has issue inside?
```

### PR DESCRIPTION
**Pull request by TommyLike**
1. Fix Seek&Read issue in SeqCursor
2. Fix md5 hash infinite loop when sign package
3. Add test for sign package and SeqCursor

Close #16

### CODE REVIEW

**Comment by TommyLike** [comment]
@drahnr @dralley Tested with generate package and signed package
````
❯ rpm -Kv awesome.rpm
awesome.rpm:
    Header V4 RSA/SHA256 Signature, key ID 9e695ea4: OK
    Header SHA1 digest: OK
    V4 RSA/SHA256 Signature, key ID 9e695ea4: OK
    MD5 digest: OK

rpm-rs-2/test_assets/verify_rust_rpm [ master][✘+?][🦀 v1.64.0]
❯ rpm -Kv awesome.rpm.rs
awesome.rpm.rs:
    Header V4 RSA/SHA256 Signature, key ID 9e695ea4: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA256 Signature, key ID 9e695ea4: OK
    MD5 digest: OK
````

**Comment by drahnr** [comment]
Hey @TommyLike , thanks for taking care of fixing it, very much appreciated!

Could you add a regression test for the `SeqCursor` fix and split out the unrelated changes into a second PR/multiple PRs

**Comment by TommyLike** [comment]
@drahnr sure, PR updated.

File: src/sequential_cursor.rs [hunk 1]
```diff
@@ -106,4 +110,48 @@ mod test {
...
+            buf.set_len(2 * 3);
+        }
+        // without seek
+        let mut sq = SeqCursor::new(&[c1.as_slice(), c2.as_slice(), c3.as_slice()]);
+        sq.read(&mut buf).unwrap();
+        assert_eq!(buf.to_vec(), vec![1u8, 1u8, 2u8, 2u8, 3u8, 3u8]);
+
+        // seek with start
+        buf = Vec::<u8>::with_capacity(5);
+        unsafe {
```
Comment (drahnr) [inline src/sequential_cursor.rs:131]: `vec![0u8; 5]`

File: src/sequential_cursor.rs [hunk 2]
```diff
@@ -50,15 +52,17 @@ impl<'s> std::io::Read for SeqCursor<'s> {
             acc_offset += chunk_len;
             if self.position < acc_offset as u64 {
                 let remaining_in_chunk = (acc_offset as u64 - self.position) as usize;
+                let start = (chunk_len - remaining_in_chunk) as u64;
                 let fin = std::cmp::min(total_read + remaining_in_chunk, buf.len());
+                cursor.seek(SeekFrom::Start(start))?;
```
Comment (drahnr) [inline src/sequential_cursor.rs:57]: We could seek to `0` at the beginning in the loop

File: src/sequential_cursor.rs [hunk 3]
```diff
@@ -106,4 +110,48 @@ mod test {
...
+        sq.seek(SeekFrom::Start(0)).unwrap();
+        sq.seek(SeekFrom::Current(1)).unwrap();
+        sq.read(&mut buf).unwrap();
+        assert_eq!(buf.to_vec(), vec![1u8, 2u8, 2u8, 3u8, 3u8]);
+
+        //seek with end
+        buf = Vec::<u8>::with_capacity(3);
+        unsafe {
+            buf.set_len(3);
+        }
```
Comment (drahnr) [inline src/sequential_cursor.rs:152]:
```suggestion
        buf = vec![0u8; 3];
```

File: src/sequential_cursor.rs [hunk 4]
```diff
@@ -106,4 +110,48 @@ mod test {
...
+        sq.seek(SeekFrom::Start(1)).unwrap();
+        sq.read(&mut buf).unwrap();
+        assert_eq!(buf.to_vec(), vec![1u8, 2u8, 2u8, 3u8, 3u8]);
+
+        //seek with current
+        buf = Vec::<u8>::with_capacity(5);
+        unsafe {
+            buf.set_len(5);
+        }
```
Comment (drahnr) [inline src/sequential_cursor.rs:142]:
```suggestion
        buf = vec![0u8; 5]
```

**Comment by TommyLike** [comment]
@drahnr done.

**Comment by drahnr** [comment]
Once #21 is merged, and this is ready to go!

File: src/sequential_cursor.rs (hunk 2 above)
Comment (drahnr) [reply src/sequential_cursor.rs:57]: Could you elaborate why this was closed as resolved?

File: src/sequential_cursor.rs [hunk 5]
```diff
@@ -72,7 +76,7 @@ impl<'s> std::io::Seek for SeqCursor<'s> {
                     .cursors
                     .iter()
                     .fold(0u64, |acc, cursor| acc + cursor.get_ref().len() as u64);
-                (total as i64 - rel) as u64
+                (total as i64 + rel) as u64
```
Comment (drahnr) [inline src/sequential_cursor.rs:79]: Thank you! The notion of `FromEnd` was apparently not clear to me at the time of impl. I double checked in this is correct CC @dralley

**Review by drahnr — APPROVED** [review]

File: src/sequential_cursor.rs (hunk 2 above)
Comment (TommyLike) [reply src/sequential_cursor.rs:57]: thanks @drahnr , let me explain here:
Your suggestion will fail when reading Seqcursor with a short buffer, cause it will always start from zero, I added another testcase for this.

**Comment by drahnr** [comment]
Could you rebase the PR to make clippy happy?

**Review by drahnr — APPROVED** [review]

**Review by drahnr — APPROVED** [review]

**Comment by drahnr** [comment]
@dralley fix is sane, could you give a quick review?

File: src/sequential_cursor.rs [hunk 6]
```diff
@@ -72,7 +76,7 @@ impl<'s> std::io::Seek for SeqCursor<'s> {
                     .cursors
                     .iter()
                     .fold(0u64, |acc, cursor| acc + cursor.get_ref().len() as u64);
```
Comment (dralley) [inline src/sequential_cursor.rs:78]: Can `let total =` be collapsed into `self.len`?  It looks like it's just calculating that length of all the slices underlying the cursors on the fly, but we're already keeping track of that.

Comment (drahnr) [reply src/sequential_cursor.rs:78]: That's unrelated to the fix presented, and I'd prefer to get this merged ASAP rather than pull in more change of lines that were not touched.

Comment (TommyLike) [reply src/sequential_cursor.rs:78]: @dralley I would not change this in current PR.

File: src/sequential_cursor.rs (hunk 5 above)
Comment (dralley) [reply src/sequential_cursor.rs:79]: @drahnr @TommyLike As this transformed from `-` to `+`, the `as i64` shouldn't be necessary any longer

Comment (dralley) [reply src/sequential_cursor.rs:79]: I take it back, might depend on the variant of  `SeekFrom` https://doc.rust-lang.org/stable/std/io/enum.SeekFrom.html
